### ISSUE TITLE
Fetch block chain tip without subscribing

### ISSUE THREAD

**Issue by dagurval** [dagurval/electrum-cash-protocol#9]
Currently it looks like you have to subscribe to headers if you want to know the block chain tip

**Comment by cculianu** [comment]
Hmm. Yeah I guess that's an imperfection.  `blockchain.headers.gettip`? `get_tip`?  `tip`?

**Comment by dagurval** [comment]
It's kind of annoying when I just want to hack together a script that pulls the tip every few seconds. Now I have to do the proper way :-).

**Comment by dagurval** [comment]
I like `blockchain.headers.tip`.

it's kind of weird though when the two existing header methods are under `blockchain.block`, while one is in `blockchain.headers`.

**Comment by cculianu** [comment]
Ah yeah that makes sense. And I believe right now it actually complains that you're already subscribed, right? IIRC...

> I like blockchain.headers.tip.

So do I. Feel free to go with that one.  I guess takes 0 parameters `[]` and returns the same result you'd get from `headers.subscribe`, right?

**Comment by dagurval** [comment]
>  I guess takes 0 parameters [] and returns the same result you'd get from headers.subscribe, right?

:+1:

**Comment by dagurval** [comment]
Closing in favour of #20
